import { useState } from 'react';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import * as z from "zod";
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import {
    Form,
    FormControl,
    FormDescription,
    FormField,
    FormItem,
    FormLabel,
    FormMessage,
} from "@/components/ui/form";


const formSchema = z.object({
    // "litigation_id": this be auto-generated by the system
    "name": z.string().min(1).max(40),
    // "summary": z.string().min(1).max(255),
    // "country": z.string().min(1).max(255),
    // "type": z.string().min(1).max(255),
    // "link": z.string().url(),
    // "status": z.string().min(1).max(255),
    // "mandate": z.string().min(1).max(255),
    // "jurisdiction": z.string().min(1).max(255),
    // "entity": z.string().min(1).max(255),
    // "sub_entity": z.string().min(1).max(255),
    // "notes": z.string().min(1).max(255),
});
export default function PolicyForm() {
    const [formData, setFormData] = useState({
        // policy_id: '',
        name: '',
        summary: '',
        country: '',
        type: '',
        link: '',
        status: '',
        mandate: '',
        jurisdiction: '',
        entity: '',
        sub_entity: '',
        notes: '',
        tags: '',
    });
    const form = useForm({
        resolver: zodResolver(formSchema),
        defaultValues: {
    },
      })
    
      function onSubmit(values) {
        console.log(values)
      }


    return (

        <Form {...form}>
        <form noValidate onSubmit={form.handleSubmit(onSubmit)} className="space-y-8">
              
              <FormField
                control={form.control}
                name="name"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Name</FormLabel>
                    <FormControl>
                      <Input type="name" placeholder="Name" {...field} />
                    </FormControl>
                  </FormItem>
                )}
              />

          <Button type="submit">Submit</Button>
        </form>
      </Form>
    );
}